### PR TITLE
add support for filtering on derived types to entity collection requests

### PR DESCRIPTION
**Pull request by davidmoten**
as discussed in #8 this should work. I'll confirm when I write a unit test for it. I already have a unit test somewhere that returns a collection of Attachment and the objects returned in the list are of type ItemAttachment,  FileAttachment so I should be able to reuse that data.

### CODE REVIEW

**Comment by davidmoten** [comment]
Yep, tests working now. Can you review please @badfish69?

**Comment by badfish69** [comment]
Awesome!  Confirming that it works as expected at my end, in fact much better as it now generates the correct entity objects.

**Comment by davidmoten** [comment]
>Awesome! Confirming that it works as expected at my end, in fact much better as it now generates the correct entity objects.

Cool. Did you do a live test, as in you connected to MsGraph API and it worked?

**Comment by davidmoten** [comment]
I've merged. Further feedback on the topic welcome of course.

**Comment by badfish69** [comment]
> > Awesome! Confirming that it works as expected at my end, in fact much better as it now generates the correct entity objects.
> 
> Cool. Did you do a live test, as in you connected to MsGraph API and it worked?

Yes, was tested on a real endpoint /group/members.  Worked perfectly.

**Comment by davidmoten** [comment]
@badfish69, thank you very much for the PRs, all 3 merged and deployed to Maven Central as 0.1.13.

**Pull request merged**
